
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role-backup
rules:
- apiGroups:
  - ops.dac.nokia.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
