# Copyright 2021 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manager-rolebinding-backup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manager-role-backup
subjects:
- kind: ServiceAccount
  name: controller-manager-backup
  