# Copyright 2022 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: consul-backup-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: consul-backup-role
subjects:
- kind: ServiceAccount
  name: consul-backup-service-account
  