
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: consul-backup-role
rules:
- apiGroups:
  - ops.dac.nokia.com
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
