name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Download component test binaries
      run: make componenttest
      working-directory: ./consul-operator
    - name: Build consul-operator
      run: make docker-build IMG=consul-operator:test
      working-directory: ./consul-operator
    - name: Build alarmlogger
      run: go build -v ./...
      working-directory: ./alarmlogger
    - name: Test alarmlogger
      run: go test -v ./...
      working-directory: ./alarmlogger
    - name: Build component-test library
      run: go build -v ./...
      working-directory: ./componenttest-lib
    - name: Test component-test library
      run: go test -v ./...
      working-directory: ./componenttest-lib
